### PR TITLE
Footer Updated

### PR DESCRIPTION
**Pull request by jsvigneshkanna**
@Krishna1922 

Description:
Footer added as same as facebook  login page

Issue: #4 

Screenshot:
image

### CODE REVIEW

**Comment by jsvigneshkanna** [comment]
@Krishna1922 ,

Kindly add `hacktoberfest` label in repo so that PR would be considered for hacktoberfest

**Comment by jsvigneshkanna** [comment]
@Krishna1922 
The PR should be labeled as `hacktoberfest-accepted`

**Comment by Krishna1922** [comment]
not responsive make it responsive @jsvigneshkanna

**Comment by jsvigneshkanna** [comment]
@Krishna1922 , made responsive

image

**Pull request merged**
